"""schemat bazowy MVP

Revision ID: 93e268531fa6
Revises: 
Create Date: 2026-07-02 19:13:01.236490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e268531fa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('forwarders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'logistics', 'warehouse', 'forwarder', name='role'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('forwarder_id', sa.Integer(), nullable=True),
    sa.Column('view_all_companies', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['forwarder_id'], ['forwarders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('default_daily_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('calendar_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'day')
    )
    op.create_table('daily_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'day')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_no', sa.String(length=11), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('forwarder_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ZAPOWIEDZIANY', 'W_TRANSPORCIE', 'W_PORCIE', 'ODPRAWA', 'AWIZOWANY', 'W_DOSTAWIE', 'DOSTARCZONY', 'ZREALIZOWANY', name='containerstatus'), nullable=False),
    sa.Column('customs_status', sa.Enum('BRAK', 'DOKUMENTY_KOMPLETNE', 'ZLECONA', 'ODPRAWIONY', 'REWIZJA', name='customsstatus'), nullable=False),
    sa.Column('customs_note', sa.Text(), nullable=False),
    sa.Column('customs_date', sa.Date(), nullable=True),
    sa.Column('customs_agency', sa.String(length=160), nullable=False),
    sa.Column('vessel', sa.String(length=160), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('notify_date', sa.Date(), nullable=True),
    sa.Column('proposed_delivery_date', sa.Date(), nullable=True),
    sa.Column('transport_type', sa.Enum('kola', 'kolej', 'inne', name='transporttype'), nullable=True),
    sa.Column('transport_details', sa.String(length=200), nullable=False),
    sa.Column('container_size', sa.String(length=40), nullable=False),
    sa.Column('documents_ok', sa.Boolean(), nullable=False),
    sa.Column('demurrage_free_days', sa.Integer(), nullable=True),
    sa.Column('incoming_delivery_no', sa.String(length=80), nullable=False),
    sa.Column('rf_number', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tracked_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_error', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['forwarder_id'], ['forwarders.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containers_company_id'), 'containers', ['company_id'], unique=False)
    op.create_index(op.f('ix_containers_container_no'), 'containers', ['container_no'], unique=False)
    op.create_index(op.f('ix_containers_notify_date'), 'containers', ['notify_date'], unique=False)
    op.create_index(op.f('ix_containers_status'), 'containers', ['status'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_attachments_container_id'), 'attachments', ['container_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_container_id'), 'messages', ['container_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('vessel', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id', 'event_code', 'occurred_at', 'location')
    )
    op.create_index(op.f('ix_tracking_events_container_id'), 'tracking_events', ['container_id'], unique=False)
    op.create_table('transport_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('forwarder_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WYSTAWIONE', 'ZAAKCEPTOWANE', 'ODRZUCONE', 'W_REALIZACJI', 'WYKONANE', 'POTWIERDZONE', name='transportorderstatus'), nullable=False),
    sa.Column('pickup_location', sa.String(length=200), nullable=False),
    sa.Column('delivery_location', sa.String(length=200), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['forwarder_id'], ['forwarders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_orders_company_id'), 'transport_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_transport_orders_container_id'), 'transport_orders', ['container_id'], unique=False)
    op.create_index(op.f('ix_transport_orders_forwarder_id'), 'transport_orders', ['forwarder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transport_orders_forwarder_id'), table_name='transport_orders')
    op.drop_index(op.f('ix_transport_orders_container_id'), table_name='transport_orders')
    op.drop_index(op.f('ix_transport_orders_company_id'), table_name='transport_orders')
    op.drop_table('transport_orders')
    op.drop_index(op.f('ix_tracking_events_container_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_container_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_attachments_container_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_containers_status'), table_name='containers')
    op.drop_index(op.f('ix_containers_notify_date'), table_name='containers')
    op.drop_index(op.f('ix_containers_container_no'), table_name='containers')
    op.drop_index(op.f('ix_containers_company_id'), table_name='containers')
    op.drop_table('containers')
    op.drop_table('orders')
    op.drop_table('daily_limits')
    op.drop_table('calendar_days')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('ports')
    op.drop_table('forwarders')
    op.drop_table('companies')
    op.drop_table('carriers')
    # ### end Alembic commands ###
